#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ProjektZaliczeniowyXamarin.Resource", IsApplication=true)]

namespace ProjektZaliczeniowyXamarin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int enter_from_down = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int enter_from_left = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int enter_from_right = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int enter_from_top = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int exit_to_down = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int exit_to_left = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int exit_to_right = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int exit_to_top = 2130968583;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050003
			public const int blue = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int blueFocused = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int bluePressed = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int green = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int greenFocused = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int greenPressed = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int orange = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int orangeFocused = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int orangePressed = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int red = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int redFocused = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int redPressed = 2131034119;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int About = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int aboutButtonSelector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Find = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int findButtonSelector = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int History = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int historyButtonSelector = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int labout = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int lfind = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int lhistory = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int lstatistics = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Statistics = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int statisticsButtonSelector = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000d
			public const int CityArea = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int CityName = 2131165195;
			
			// aapt resource value: 0x7f07000e
			public const int DateTime = 2131165198;
			
			// aapt resource value: 0x7f070006
			public const int MyButton = 2131165190;
			
			// aapt resource value: 0x7f07000c
			public const int StreetAddress = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int aboutButton = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int camera_preview = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int findButton = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int historyButton = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int linear_profile = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int loading_spinner = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int myListView = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int myTextContent = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int myTextView = 2131165194;
			
			// aapt resource value: 0x7f070002
			public const int statisticsButton = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int aboutLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int beginLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int findLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int historyLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int statisticsLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int view_row = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060009
			public const int AboutInfo = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int ApplicationName = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int DistInfo = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int TotalArea = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int WaitForGpsInfo = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int aboutText = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int beginText = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int findText = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int historyText = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int statisticsText = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
